from smolagents.agents import BaseAgent

class EmailAgent(BaseAgent):
    def __init__(self, tools):
        """
        Initializes the EmailAgent with a list of tools.
        This makes the agent modular and allows custom tool configurations.

        Args:
            tools (list): A list of instantiated Tool objects (e.g., [WriteEmail(), SendEmail()])
        """
        super().__init__(tools=tools)

    def run(self, user_input):
        """
        Handles user input and routes it through the BaseAgent's chat method.

        Args:
            user_input (str): The message or command from the user.

        Returns:
            str: The response generated by the agent using its tools.
        """
        return self.chat(user_input)
